services:
  app:
    build:
      context: .
      dockerfile: .dockerfile/Dockerfile
    image: "${CONTAINER_NAME_PREFIX}-app"
    ports:
      - "${APP_PORT}:80"
    volumes:
      - volume:/var/www/html
    container_name: "${CONTAINER_NAME_PREFIX}-app"
    restart: unless-stopped
    networks:
      - net-geometry-mart-admin-network

volumes:
  volume:

networks:
  net-geometry-mart-admin-network:
    external: true
